#ifndef __Dialog_Interface__
#define __Dialog_Interface__

/**
@file
Subclass of ControlDialog, which is generated by wxFormBuilder.
*/

#include "include/Layout.h"

//// end generated include

#include "include/Config.h"
class MainFrame_Interface;

/** Implementing ControlDialog */
class Dialog_Interface : public ControlDialog
{
	protected:
		// Handlers for ControlDialog events.
		void OnExit( wxCloseEvent& event );
		void DisplayEquationOnButtonClick( wxCommandEvent& event );
		void ChoiceListOnListBox( wxCommandEvent& event );
		void PlaneEnableOnToggleButton( wxCommandEvent& event );
		void PlaneCtrlOnScroll( wxScrollEvent& event );
		void PlaneCtrlOnSlider( wxCommandEvent& event );
		void X_MinCtrlOnSpinCtrlDouble( wxSpinDoubleEvent& event );
		void X_MinCtrlOnSpinCtrlText( wxCommandEvent& event );
		void X_MaxCtrlOnSpinCtrlDouble( wxSpinDoubleEvent& event );
		void X_MaxCtrlOnSpinCtrlText( wxCommandEvent& event );
		void Y_MinCtrlOnSpinCtrlDouble( wxSpinDoubleEvent& event );
		void Y_MinCtrl1OnSpinCtrlText( wxCommandEvent& event );
		void Y__MaxCtrlOnSpinCtrlDouble( wxSpinDoubleEvent& event );
		void Y_MaxCtrlOnSpinCtrlText( wxCommandEvent& event );
		void Z_MinCtrlOnSpinCtrlDouble( wxSpinDoubleEvent& event );
		void Z_MinCtrlOnSpinCtrlText( wxCommandEvent& event );
		void Z_MaxCtrlOnSpinCtrlDouble( wxSpinDoubleEvent& event );
		void Z_MaxCtrlOnSpinCtrlText( wxCommandEvent& event );
		void PrecisionCtrlOnScroll( wxScrollEvent& event );
		void PrecisionCtrlOnSlider( wxCommandEvent& event );
		void ColorRadioOnRadioButton( wxCommandEvent& event );
		void LengthRadioOnRadioButton( wxCommandEvent& event );
		void ArrowCtrlOnScroll( wxScrollEvent& event );
		void ArrowCtrlOnSlider( wxCommandEvent& event );

	public:
		/** Constructor */
		Dialog_Interface( wxWindow* parent );
	//// end generated class members
		
		void SetPlane();
		void Setup();
		Dialog_Interface(Config* config, wxWindow* parent);
		Config* current_config;
		MainFrame_Interface* parent;
	private:
		void Refresh();
};

#endif // __Dialog_Interface__
