#ifndef __HelpDialog_Interface__
#define __HelpDialog_Interface__

/**
@file
Subclass of HelpDialog, which is generated by wxFormBuilder.
*/

#include "include/Layout.h"

class MainFrame_Interface;

//// end generated include

/** Implementing HelpDialog */
class HelpDialog_Interface : public HelpDialog
{
	protected:
		// Handlers for HelpDialog events.
		void OnExit( wxCloseEvent& event );
	public:
		/** Constructor */
		HelpDialog_Interface( MainFrame_Interface* parent );
	//// end generated class members
		MainFrame_Interface* parent;

};

#endif // __HelpDialog_Interface__
