#ifndef __MainFrame_Interface__
#define __MainFrame_Interface__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "include/Layout.h"

//// end generated include

#pragma once
#include "include/Dialog_Interface.h"
#include "include/Config.h"
#include <wx/msgdlg.h>
#include <wx/dcbuffer.h>
#include "include/Draw.h"
#include "include/Primitives.h"
#include "include/ControlParam_Interface.h"
#include "include/HelpDialog_Interface.h"
#include <wx/filedlg.h>
#include <wx/dirdlg.h>

/** Implementing MainFrame */
class MainFrame_Interface : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void OnExit( wxCloseEvent& event );
		void Refresh( wxUpdateUIEvent& event );
		void m_ControlPanelSelection( wxCommandEvent& event );
		void m_FunctionConfigSelection( wxCommandEvent& event );
		void m_SaveAsSelection( wxCommandEvent& event );
		void m_QuitSelection( wxCommandEvent& event );
		void m_AboutSelection( wxCommandEvent& event );
		void m_HelpSelection( wxCommandEvent& event );
		void DrawCanvasOnLeftDown( wxMouseEvent& event );
		void DrawCanvasOnLeftUp( wxMouseEvent& event );
		void DrawCanvasOnMotion( wxMouseEvent& event );
		void DrawCanvasOnMouseWheel( wxMouseEvent& event );

	public:
		/** Constructor */
		MainFrame_Interface( wxWindow* parent );
	//// end generated class members
		~MainFrame_Interface();
		void CheckHandler(std::string name);
		void OpenDialog(Function* fun);
		void CloseDialog(Function* fun);

		Dialog_Interface* controldialog;
		HelpDialog_Interface* helpdialog;
		ControlParam_Interface* controlparam;
		Config* current_config;
		std::vector<Segment> data;
		std::vector<Segment> arrow;
		std::vector<Function*> fun_list;

		wxBitmap _pic;
		wxImage MyImage;
};

#endif // __MainFrame_Interface__
